#!/bin/bash

case "$1" in
+)
  brightnessctl set 2%+
  ;;
-)
  brightnessctl set 2%-
  ;;
*)
  echo "Uso [_____ + ____|______ - _____]"
  echo "    [ Aumenta el | Disminuye el ]"
  echo "    [ brillo en  | brillo en    ]"
  echo "    [ un 2%.     | un 2%.       ]"
  ;;
esac